### ISSUE TITLE
Track DeprecatedFlyString

### ISSUE THREAD

**Issue by AtkinsSJ** [BenWiederhake/serenity-fixmes#7]
There's over 1000 of them right now, and they're ignored by the tracking. It'd be nice to graph them alongside the DeprecatedStrings.

(I did attempt this briefly but I don't know gnuplot, or Python really. :sweat_smile: )

**Comment by BenWiederhake** [comment]
Hmm. In the ideal solution, all three stats (FIXMEs, Deprecated{Fly,}String) would be in the same graph, and you could easily scroll around in it. However, it's a problem of scale: 1000 DFlyStrings would barely register on the DString graph. So it would have to be a third graph, which gets a bit silly.

I could take care of the data extraction and updates, but I don't feel good about just adding yet another graph. Can you come up with an idea of how to combine this reasonably?

Using log scale doesn't really fix the problem, because then the day-to-day changes aren't visible anymore. Independent y-axes also feel like a cheat, and it works only a few times before becoming confusing.

**Comment by AtkinsSJ** [comment]
My original attempt was just changing the grep from
```
        ["git", "-C", SERENITY_DIR, "grep", "-F", "DeprecatedString"], 
```

to

```
        ["git", "-C", SERENITY_DIR, "grep", "-iE", "DeprecatedString|DeprecatedFlyString"], 
```

which would count them together. Maybe that's not so bad?

**Comment by BenWiederhake** [comment]
That would leave a few edge cases, but that's not really the thing I'm worried about. I'm rather worried about presentation on the website: See above for my reasoning on that.

**Comment by BenWiederhake** [comment]
Derp, only now I really understand what you were saying: Only track a single number, which is the combined count; no splitting up needed.

Yes, I'll do that. And because that requires recomputing a bunch of the numbers, I'll do it slightly different, perhaps, if I find the time for it ^^

**Comment by AtkinsSJ** [comment]
Hehe, no worries. Yeah the two classes are connected enough that one line is probably fine imo.

**Comment by BenWiederhake** [comment]
Done! https://benwiederhake.github.io/serenity-fixmes/

The reason it took a bit more effort was that "old" commit statistics had to be recomputed. While at it, I also took the executive decision to ignore binary files. This *might* affect old commits slightly, but I'm not really into burning ~10k CPU seconds single-core in order to fix these marginally-off numbers. The "jump" isn't even visible:

![Bildschirmfoto_2023-02-15_22-17-44](https://user-images.githubusercontent.com/2690845/219168376-147d0f44-dfbc-4d75-8d21-4894225aeac8.png)

**Comment by AtkinsSJ** [comment]
Great! :grinning:
